apiVersion: apps/v1
kind: Deployment
metadata:
  name: info-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: info-service
  template:
    metadata:
      labels:
        app: info-service
    spec:
      containers:
      - name: info-service
        image: info-service:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /info
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /info
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 3
