apiVersion: v1
kind: Service
metadata:
  name: info-service
spec:
  selector:
    app: info-service
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30080
